version: '3.1'
services:

  dboracle:
    image: gvenzl/oracle-xe:slim
    ports:
      - "1521:1521"
    env_file:
      - .env
    environment:
      ORACLE_DATABASE: ${ORACLE_DATABASE}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_USER_PASSWORD}

  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
